services:
  pgvector-db:
    image: pgvector/pgvector:pg16 # pgvectorが最初から入っている公式イメージ
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_vector_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # SQLファイルを自動実行させる設定

volumes:
  pgdata:
